debug:
  console: false
  players: false
tool:
  block: LAPIS_ORE
  item: BLAZE_ROD
bucket:
  enabled: true
  safe: true
dispenser:
  enabled: true
  safe: true
flowsel:
  enabled: true
  maxsize: 0
