name: SafeBuckets
main: nu.nerd.SafeBuckets.SafeBuckets
version: ${project.version}
description: ${project.description}
website: ${project.url}
database: true
authors: [Travis Watkins, Ed Kellett, Stephen McGregor, totemo, redwall_hp, bermudalocket]
depend: [BlockStore]
softdepend: [WorldEdit, WorldGuard]
loadbefore: [Multiverse-Core]
api-version: 1.14

permissions:
  safebuckets.debug:
    description: Permission to recieve debug messages if enabled in config.
  safebuckets.playerflow:
    description: Permission to use the /flow command.
  safebuckets.tools.item:
    description: Permission to use the SafeBuckets inspector tool item.
  safebuckets.tools.block:
    description: Permission to use the SafeBuckets inspector block.
  safebuckets.tools.unsafe:
    description: Permission to summon an unsafe liquid bucket.
  safebuckets.tools.norefill:
    description: Players with this permission do not need to refill the unsafe buckets they empty.
  safebuckets.flowsel:
    description: Permission to use `/sb flowsel`.
  safebuckets.safesel:
    description: Permission to use `/sb safesel`.
  safebuckets.reload:
    description: Permission to use `/sb reload`.
  safebuckets.override:
    description: Players with this permission are not restricted to the flowsel/safesel area limit.

commands:
  sb:
    description: SafeBuckets moderator command.
    usage: |
    
      §e/<command> reload§f - Reload the SafeBuckets configuration.
      §e/<command> §eflowsel§f - Flow all safe liquid blocks in the current WorldEdit selection.
      §e/<command> §f[§etype§f [§esafe§f|§eunsafe§f]] - Convert the player's empty hotbar slot or some kind of bucket into a bucket with the specified safety and liquid type. If the arguments do not specify safety, turn an empty slot or bucket into an unsafe water bucket, or invert the safety of another held bucket. If the slot is not empty or a valid bucket, an attempt will be made to convert the held item, but upon failure will not give the player any item. If the liquid is not specified, it defaults to water.
    
  flow:
    description: Toggle "flow mode" on or off.
    usage: |
    
      §e/<command>§f - Toggle "flow mode" on or off. When on, a player can click a liquid block to make it flow in regions where they have build permission, or regions they own, depending on the configuration.
